# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: FreePBX
version: "0.0.1"
slug: freepbx
description: FreePBX is a web-based open-source graphical user interface that manages Asterisk, a voice over IP and telephony server. 
url: "https://github.com/juanjoSanz/FreePBX-hass-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant_api: true
map:
  - share:rw
  - config:rw
  - ssl
options:
  test_op: test
schema:
  test_schema: test
image: "ghcr.io/juanjoSanz/{arch}-addon-freepbx"
host_network: true
init: false
uart: true 